groups:
  # ─── Service Availability ────────────────────────────────────────────────────
  - name: service_availability
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
          /
          sum(rate(http_requests_total[5m])) by (service)
          > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.service }}"
          description: "{{ $labels.service }} has a 5xx error rate of {{ $value | humanizePercentage }} over the last 5 minutes."

      - alert: CriticalErrorRate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
          /
          sum(rate(http_requests_total[5m])) by (service)
          > 0.20
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical error rate on {{ $labels.service }}"
          description: "{{ $labels.service }} has a 5xx error rate of {{ $value | humanizePercentage }}."

  # ─── Latency ─────────────────────────────────────────────────────────────────
  - name: latency
    rules:
      - alert: HighP99Latency
        expr: |
          histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service))
          > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High P99 latency on {{ $labels.service }}"
          description: "P99 latency for {{ $labels.service }} is {{ $value | humanizeDuration }}."

      - alert: CriticalP99Latency
        expr: |
          histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service))
          > 10.0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical P99 latency on {{ $labels.service }}"
          description: "P99 latency for {{ $labels.service }} is {{ $value | humanizeDuration }}."

  # ─── Resource Usage ──────────────────────────────────────────────────────────
  - name: resource_usage
    rules:
      - alert: HighCPUUsage
        expr: |
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanize }}% on {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanize }}% on {{ $labels.instance }}."

      - alert: DiskSpaceLow
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is {{ $value | humanize }}% available on {{ $labels.instance }}."

      - alert: DiskSpaceCritical
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: "Disk space is {{ $value | humanize }}% available on {{ $labels.instance }}."

  # ─── Database ────────────────────────────────────────────────────────────────
  - name: database
    rules:
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is not responding."

      - alert: PostgreSQLHighConnections
        expr: |
          pg_stat_activity_count / pg_settings_max_connections > 0.80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL connection pool near capacity"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of max connections."

      - alert: PostgreSQLSlowQueries
        expr: |
          rate(pg_stat_activity_max_tx_duration{state="active"}[5m]) > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Queries running longer than 30 seconds detected."

      - alert: PostgreSQLReplicationLag
        expr: pg_replication_lag > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL replication lag"
          description: "Replication lag is {{ $value | humanizeDuration }}."

  # ─── Resume Parser Specific ──────────────────────────────────────────────────
  - name: resume_parser
    rules:
      - alert: ResumeParseFailureRate
        expr: |
          sum(rate(resume_parse_failures_total[5m]))
          /
          sum(rate(resume_parse_requests_total[5m]))
          > 0.10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High resume parse failure rate"
          description: "Resume parse failure rate is {{ $value | humanizePercentage }}."

  # ─── Job Aggregator Specific ─────────────────────────────────────────────────
  - name: job_aggregator
    rules:
      - alert: JobScrapingFailed
        expr: |
          time() - job_aggregator_last_successful_scrape_timestamp > 7200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Job scraping has not run recently"
          description: "Last successful job scrape was {{ $value | humanizeDuration }} ago."
